// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsnnphgangdcisquxghj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zbm5waGdhbmdkY2lzcXV4Z2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODYyMDIsImV4cCI6MjA2NDM2MjIwMn0.NL_nSxh4fq2qKb3JoGAih-htYevELlI3tDdntmgd4Ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);